In [ ]:
import pandas as pd

In [ ]:
data = {
    'Eid': [1,2,3,4,5,6,7,8,9,10],
    'Esalary': [50000,40000,30000,20000,45000,55000,60000,25000,30000,67000]
}
df = pd.DataFrame(data)
display(df.head())

   Eid  Esalary
0    1    50000
1    2    40000
2    3    30000
3    4    20000
4    5    45000

In [ ]:
df.shape

(10, 2)

In [ ]:
display(df['Esalary'])

0    50000
1    40000
2    30000
3    20000
4    45000
5    55000
6    60000
7    25000
8    30000
9    67000
Name: Esalary, dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Eid      10 non-null     int64
 1   Esalary  10 non-null     int64
dtypes: int64(2)
memory usage: 292.0 bytes

In [ ]:
display(df['Esalary'])

0    50000
1    40000
2    30000
3    20000
4    45000
5    55000
6    60000
7    25000
8    30000
9    67000
Name: Esalary, dtype: int64

In [ ]:
df['Esalary'].sort_values()

3    20000
7    25000
2    30000
8    30000
1    40000
4    45000
0    50000
5    55000
6    60000
9    67000
Name: Esalary, dtype: int64

In [ ]:
mean_salary=df['Esalary'].mean()
print("Mean Salary:", mean_salary)

Mean Salary: 42200.0

In [ ]:
median_salary=df['Esalary'].median()
print("Median Salary:", median_salary)

Median Salary: 42500.0

In [ ]:
mode_salary=df['Esalary'].mode()
print("Mode Salary:", mode_salary)

Mode Salary: 0    30000
Name: Esalary, dtype: int64

In [ ]:
#Range=max-min
salary_range=df['Esalary'].max()-df['Esalary'].min()
print("Salary Range:", salary_range)

Salary Range: 47000

In [ ]:
from numpy._core.fromnumeric import var
#variance
var_salary=df['Esalary'].var()
print("Variance Salary:", var_salary)

Variance Salary: 250622222.2222222

In [ ]:
#Standard deviation
std_salary=df['Esalary'].std()
print("Standard Deviation Salary:", std_salary)

Standard Deviation Salary: 15831.052467294214

In [ ]:
#Percentiles
#Instead of asking only for the avg what is I want to know where a particular percentage of employee falls
q1=df['Esalary'].quantile(0.25)
q2=df['Esalary'].quantile(0.50)
q3=df['Esalary'].quantile(0.75)
print("Q1:", q1)
print("Q2:", q2)
print("Q3:", q3)

Q1: 30000.0
Q2: 42500.0
Q3: 53750.0

In [ ]:
#IQR(INTER QUARTILE RANGE)


#Outlier
#IQR RULE
#lower boundary: q1-1.5*iqr
#upper boundary: q3+1.5*iqr